import { EvolutionSummary, GraphEdgeData, GraphNodeData, Session, SessionLog, Task } from "../types";

export const MOCK_TASKS: Task[] = [
  {
    id: "task_reverse_shopee_01",
    name: "Shopee Checkout API Reversal",
    goal_description: "Reverse-engineer token signatures and checkout payload creation for web automation.",
    instructions: "Navigate to product page, add to cart, proceed to checkout, and capture cryptographic signing flow.",
    env_vars: {
      TARGET_ENV: "production",
      PROXY_REGION: "VN",
      ANTI_BOT_LEVEL: "high",
    },
    initial_urls: [
      "https://shopee.vn/api/v4/item/get?itemid=12345",
      "https://shopee.vn/api/v4/cart/add_to_cart",
      "https://shopee.vn/api/v4/checkout/get",
    ],
    browser_config: {
      headless: false,
      use_cloakbrowser: true,
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
      custom_headers: {
        "x-requested-with": "XMLHttpRequest",
      },
      viewport_width: 1440,
      viewport_height: 900,
    },
    status: "IN_PROGRESS",
    session_ids: ["sess_shopee_item_01", "sess_shopee_cart_02", "sess_shopee_checkout_03"],
    created_at_ns: Date.now() * 1_000_000 - 3600_000_000_000,
    updated_at_ns: Date.now() * 1_000_000,
    metadata: { author: "ReverseEngineer_Lead", tags: ["e-commerce", "anti-bot", "wasm"] },
  },
  {
    id: "task_tiktok_signature_02",
    name: "TikTok Web X-Bogus & _signature Decryption",
    goal_description: "Isolate browser canvas fingerprinting and WASM signature generator functions.",
    instructions: "Intercept feed video requests and trace back parameters '_signature' and 'X-Bogus' to the generator function.",
    env_vars: {
      DEBUG_HOOKS: "true",
      CAPTURE_CRYPTO: "true",
    },
    initial_urls: [
      "https://www.tiktok.com/api/recommend/item_list/",
      "https://www.tiktok.com/api/comment/list/",
    ],
    browser_config: {
      headless: false,
      use_cloakbrowser: true,
      viewport_width: 1280,
      viewport_height: 800,
    },
    status: "CREATED",
    session_ids: ["sess_tiktok_feed_01", "sess_tiktok_comment_02"],
    created_at_ns: Date.now() * 1_000_000 - 7200_000_000_000,
    updated_at_ns: Date.now() * 1_000_000 - 7200_000_000_000,
    metadata: { author: "SecurityTeam", tags: ["wasm", "obfuscation"] },
  },
];

export const MOCK_SESSIONS: Record<string, Session[]> = {
  task_reverse_shopee_01: [
    {
      id: "sess_shopee_item_01",
      task_id: "task_reverse_shopee_01",
      source: "browser_agent",
      name: "Session 1: Item Details & Cookie Gen",
      target: "https://shopee.vn/api/v4/item/get?itemid=12345",
      status: "COMPLETED",
      started_at_ns: Date.now() * 1_000_000 - 3000_000_000_000,
      ended_at_ns: Date.now() * 1_000_000 - 2400_000_000_000,
      event_count: 342,
      metadata: { browser: "Chrome 128 (Cloaked)", projected_nodes: 14 },
    },
    {
      id: "sess_shopee_cart_02",
      task_id: "task_reverse_shopee_01",
      source: "browser_agent",
      name: "Session 2: Add To Cart & CSRF Token",
      target: "https://shopee.vn/api/v4/cart/add_to_cart",
      status: "RUNNING",
      started_at_ns: Date.now() * 1_000_000 - 900_000_000_000,
      event_count: 512,
      metadata: { browser: "Chrome 128 (Cloaked)", pid: 14280 },
    },
    {
      id: "sess_shopee_checkout_03",
      task_id: "task_reverse_shopee_01",
      source: "browser_agent",
      name: "Session 3: Checkout Signature Synthesis",
      target: "https://shopee.vn/api/v4/checkout/get",
      status: "CREATED",
      started_at_ns: Date.now() * 1_000_000,
      event_count: 0,
      metadata: { browser: "Waiting for launch" },
    },
  ],
  task_tiktok_signature_02: [
    {
      id: "sess_tiktok_feed_01",
      task_id: "task_tiktok_signature_02",
      source: "browser_agent",
      name: "Session 1: Recommended Feed Signature",
      target: "https://www.tiktok.com/api/recommend/item_list/",
      status: "CREATED",
      started_at_ns: Date.now() * 1_000_000,
      event_count: 0,
    },
    {
      id: "sess_tiktok_comment_02",
      task_id: "task_tiktok_signature_02",
      source: "browser_agent",
      name: "Session 2: Comment List Interceptor",
      target: "https://www.tiktok.com/api/comment/list/",
      status: "CREATED",
      started_at_ns: Date.now() * 1_000_000,
      event_count: 0,
    },
  ],
};

export const MOCK_GRAPH_DATA: Record<string, { nodes: GraphNodeData[]; edges: GraphEdgeData[] }> = {
  sess_shopee_item_01: {
    nodes: [
      {
        id: "node_req_item_get",
        session_id: "sess_shopee_item_01",
        node_type: "REQUEST",
        label: "GET /api/v4/item/get",
        alias: "ItemDetailRequest",
        entity_id: "req_9921",
        properties: {
          method: "GET",
          url: "https://shopee.vn/api/v4/item/get?itemid=12345",
          headers: { "x-api-source": "pc", "cookie": "SPC_SEC_SI=v1-abcd; SPC_EC=9201" },
          status_code: 200,
          response_bytes: 8420,
        },
        created_at_ns: Date.now() * 1_000_000 - 2800_000_000_000,
      },
      {
        id: "node_func_sign_generator",
        session_id: "sess_shopee_item_01",
        node_type: "FUNCTION",
        label: "window._encryptPayload()",
        alias: "ShopeeSignerWasm",
        entity_id: "func_0042",
        properties: {
          function_name: "_encryptPayload",
          file: "bundle.core.min.js:342",
          caller: "anonymous dispatch",
          arguments: ["itemid=12345", "1727145000"],
          returns: "e4f89ac8120b4d45",
        },
        created_at_ns: Date.now() * 1_000_000 - 2750_000_000_000,
      },
      {
        id: "node_crypto_hmac",
        session_id: "sess_shopee_item_01",
        node_type: "CRYPTO",
        label: "SubtleCrypto.sign(HMAC-SHA256)",
        alias: "HMAC_RequestAuth",
        entity_id: "crypto_312",
        properties: {
          algorithm: "HMAC",
          hash: "SHA-256",
          key_id: "subtle_key_ephemeral_01",
          input_preview: "itemid=12345&timestamp=1727145000",
          output_hex: "e4f89ac8120b4d45e4f89ac8120b4d45",
        },
        created_at_ns: Date.now() * 1_000_000 - 2700_000_000_000,
      },
      {
        id: "node_storage_cookie",
        session_id: "sess_shopee_item_01",
        node_type: "STORAGE",
        label: "document.cookie['SPC_SEC_SI']",
        alias: "SessionSecurityCookie",
        entity_id: "cookie_spc_sec",
        properties: {
          key: "SPC_SEC_SI",
          domain: ".shopee.vn",
          value: "v1-a83f98c8e104b20",
          storage_type: "cookie",
        },
        created_at_ns: Date.now() * 1_000_000 - 2650_000_000_000,
      },
      {
        id: "node_val_timestamp",
        session_id: "sess_shopee_item_01",
        node_type: "VALUE",
        label: "Math.floor(Date.now() / 1000)",
        alias: "EpochTimestamp",
        entity_id: "val_ts_01",
        properties: {
          literal_value: 1727145000,
          data_type: "number",
        },
        created_at_ns: Date.now() * 1_000_000 - 2600_000_000_000,
      },
      {
        id: "node_req_cart_add",
        session_id: "sess_shopee_item_01",
        node_type: "REQUEST",
        label: "POST /api/v4/cart/add_to_cart",
        alias: "AddToCartMutation",
        entity_id: "req_cart_add_11",
        properties: {
          method: "POST",
          url: "https://shopee.vn/api/v4/cart/add_to_cart",
          body: JSON.stringify({ itemid: 12345, quantity: 1, sign: "e4f89ac8120b4d45" }),
          status_code: 200,
        },
        created_at_ns: Date.now() * 1_000_000 - 2500_000_000_000,
      },
    ],
    edges: [
      {
        id: "edge_val_to_func",
        session_id: "sess_shopee_item_01",
        source_id: "node_val_timestamp",
        target_id: "node_func_sign_generator",
        relation_type: "FLOWS_INTO",
        confidence: 0.98,
        provenance_status: "VERIFIED",
        properties: { param_index: 1 },
      },
      {
        id: "edge_cookie_to_func",
        session_id: "sess_shopee_item_01",
        source_id: "node_storage_cookie",
        target_id: "node_func_sign_generator",
        relation_type: "READS_FROM",
        confidence: 0.92,
        provenance_status: "VERIFIED",
        properties: { source_key: "SPC_SEC_SI" },
      },
      {
        id: "edge_func_to_crypto",
        session_id: "sess_shopee_item_01",
        source_id: "node_func_sign_generator",
        target_id: "node_crypto_hmac",
        relation_type: "INVOKES",
        confidence: 0.99,
        provenance_status: "VERIFIED",
        properties: {},
      },
      {
        id: "edge_crypto_to_cart",
        session_id: "sess_shopee_item_01",
        source_id: "node_crypto_hmac",
        target_id: "node_req_cart_add",
        relation_type: "ATTACHED_TO_PAYLOAD",
        confidence: 0.95,
        provenance_status: "VERIFIED",
        properties: { json_field: "sign" },
      },
      {
        id: "edge_item_to_cookie",
        session_id: "sess_shopee_item_01",
        source_id: "node_req_item_get",
        target_id: "node_storage_cookie",
        relation_type: "SETS_COOKIE",
        confidence: 0.88,
        provenance_status: "INFERRED",
        properties: { header: "Set-Cookie" },
      },
    ],
  },
};

export const MOCK_EVOLUTION_SUMMARY: EvolutionSummary = {
  total_retrospectives: 4,
  average_efficiency_rating: 8.6,
  top_missing_tools: [
    { tool: "mcp_wasm_decompiler_trace", frequency: 5 },
    { tool: "mcp_crypto_subtle_dumper", frequency: 4 },
    { tool: "mcp_cookie_signature_fuzz", frequency: 2 },
    { tool: "mcp_replay_diff_inspector", frequency: 1 },
  ],
  recent_proposals: [
    {
      name: "wasm_function_tracer",
      purpose: "Automatically hook and hook export table of WebAssembly.instantiateStreaming to log signatures",
      parameters: { hook_memory: "boolean", trace_level: "string" },
      expected_output: "List of exported symbol names with memory buffer pointers and call arg stacks",
      task_id: "task_reverse_shopee_01",
      created_at_ns: Date.now() * 1_000_000 - 1800_000_000_000,
    },
    {
      name: "crypto_key_extractor",
      purpose: "Dump SubtleCrypto CryptoKey raw exported material when CryptoKey.extractable is true or via prototype patching",
      parameters: { target_algo: "string" },
      expected_output: "Raw JWK or PKCS#8 key bytes",
      task_id: "task_tiktok_signature_02",
      created_at_ns: Date.now() * 1_000_000 - 3600_000_000_000,
    },
  ],
  common_bottlenecks: [
    { bottleneck: "Obfuscated control flow in JavaScript bundle makes function line tracing slow", frequency: 3 },
    { bottleneck: "Manual inspection required for WebSocket subprotocol binary framing", frequency: 2 },
    { bottleneck: "Canvas fingerprinting detection triggers captcha challenge occasionally", frequency: 1 },
  ],
};

export const MOCK_SESSION_LOGS: SessionLog[] = [
  {
    id: "log_retro_shopee_01",
    task_id: "task_reverse_shopee_01",
    session_id: "sess_shopee_item_01",
    log_type: "RETROSPECTIVE",
    agent_evaluation: "Reversed Shopee item detail endpoint successfully. HMAC SHA256 was captured via SubtleCrypto hook. However, tracing the internal memory layout of the WASM blob required manual hex dumps because no tool was available to decompile WASM bytecode on the fly.",
    missing_tools: ["mcp_wasm_decompiler_trace", "mcp_crypto_subtle_dumper"],
    suggested_tools: [
      {
        name: "wasm_function_tracer",
        purpose: "Automatically hook and inspect export table of WebAssembly.instantiateStreaming",
        parameters: { hook_memory: "boolean", trace_level: "string" },
        expected_output: "List of exported symbols with memory buffer pointers",
      },
    ],
    bottlenecks: [
      "Obfuscated control flow in JavaScript bundle makes function line tracing slow",
    ],
    efficiency_rating: 8.5,
    created_at_ns: Date.now() * 1_000_000 - 1800_000_000_000,
    metadata: { agent_model: "gemini-2.5-pro", session_duration_s: 48 },
  },
  {
    id: "log_retro_tiktok_01",
    task_id: "task_tiktok_signature_02",
    session_id: "sess_tiktok_feed_01",
    log_type: "RETROSPECTIVE",
    agent_evaluation: "TikTok anti-bot canvas probe detected. Need dedicated tool to auto-mock canvas to prevent fingerprinting discrepancy between headful and headless runs.",
    missing_tools: ["mcp_canvas_fingerprint_spoofer"],
    suggested_tools: [
      {
        name: "canvas_fingerprint_spoofer",
        purpose: "Normalize HTML5 Canvas toDataURL results against known device profiles",
        parameters: { profile_preset: "string" },
        expected_output: "Stable noise injected canvas stream",
      },
    ],
    bottlenecks: [
      "Canvas fingerprinting detection triggers captcha challenge occasionally",
    ],
    efficiency_rating: 7.8,
    created_at_ns: Date.now() * 1_000_000 - 3600_000_000_000,
    metadata: { agent_model: "gemini-2.5-pro" },
  },
];
