"""create_initial_lineage_tables

Revision ID: 0f927cfcfdc4
Revises: 
Create Date: 2026-09-20 01:14:16.376162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f927cfcfdc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at_ns', sa.BigInteger(), nullable=False),
    sa.Column('ended_at_ns', sa.BigInteger(), nullable=True),
    sa.Column('created_at_ns', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_ns', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_started_at_ns'), ['started_at_ns'], unique=False)

    op.create_table('function_executions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('function_name', sa.Text(), nullable=True),
    sa.Column('module_name', sa.Text(), nullable=True),
    sa.Column('source_location', sa.Text(), nullable=True),
    sa.Column('page_id', sa.Text(), nullable=True),
    sa.Column('frame_id', sa.Text(), nullable=True),
    sa.Column('parent_execution_id', sa.Text(), nullable=True),
    sa.Column('thread_id', sa.Text(), nullable=True),
    sa.Column('process_id', sa.Text(), nullable=True),
    sa.Column('started_at_ns', sa.BigInteger(), nullable=False),
    sa.Column('ended_at_ns', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('arguments_json', sa.Text(), nullable=True),
    sa.Column('return_value_ref', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('function_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_function_executions_session_id'), ['session_id'], unique=False)

    op.create_table('graph_nodes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('node_type', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('properties_json', sa.Text(), nullable=False),
    sa.Column('created_at_ns', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index('idx_graph_nodes_entity', ['session_id', 'entity_id'], unique=False)
        batch_op.create_index('idx_graph_nodes_session_type', ['session_id', 'node_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_nodes_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_nodes_node_type'), ['node_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_nodes_session_id'), ['session_id'], unique=False)

    op.create_table('replay_plans',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('target_request_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('policy_json', sa.Text(), nullable=False),
    sa.Column('created_at_ns', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replay_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replay_plans_session_id'), ['session_id'], unique=False)

    op.create_table('trace_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('timestamp_ns', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Text(), nullable=True),
    sa.Column('frame_id', sa.Text(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('parent_execution_id', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=True),
    sa.Column('ingested_at_ns', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('trace_events', schema=None) as batch_op:
        batch_op.create_index('idx_events_execution', ['execution_id'], unique=False)
        batch_op.create_index('idx_events_session_time', ['session_id', 'timestamp_ns'], unique=False)
        batch_op.create_index('idx_events_type_time', ['event_type', 'timestamp_ns'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_events_execution_id'), ['execution_id'], unique=False)

    op.create_table('value_observations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('value_ref', sa.Text(), nullable=True),
    sa.Column('value_hash', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('value_length', sa.Integer(), nullable=True),
    sa.Column('json_path', sa.Text(), nullable=True),
    sa.Column('variable_name', sa.Text(), nullable=True),
    sa.Column('sensitivity', sa.Text(), nullable=False),
    sa.Column('redacted_value', sa.Text(), nullable=True),
    sa.Column('first_seen_at_ns', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('value_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_value_observations_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_value_observations_value_hash'), ['value_hash'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provenance_status', sa.Text(), nullable=False),
    sa.Column('properties_json', sa.Text(), nullable=False),
    sa.Column('created_at_ns', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'source_id', 'target_id', 'relation_type', name='uq_graph_edge')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index('idx_edges_confidence', ['confidence'], unique=False)
        batch_op.create_index('idx_edges_session_relation', ['session_id', 'relation_type'], unique=False)
        batch_op.create_index('idx_edges_source_relation', ['source_id', 'relation_type'], unique=False)
        batch_op.create_index('idx_edges_target_relation', ['target_id', 'relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_session_id'), ['session_id'], unique=False)

    op.create_table('network_requests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('page_id', sa.Text(), nullable=True),
    sa.Column('frame_id', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_template', sa.Text(), nullable=True),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('query_json', sa.Text(), nullable=True),
    sa.Column('headers_json', sa.Text(), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('initiator_type', sa.Text(), nullable=True),
    sa.Column('started_at_ns', sa.BigInteger(), nullable=False),
    sa.Column('completed_at_ns', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['trace_events.event_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_requests_session_id'), ['session_id'], unique=False)

    op.create_table('replay_steps',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('replay_plan_id', sa.Text(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Text(), nullable=False),
    sa.Column('target_node_id', sa.Text(), nullable=True),
    sa.Column('dependencies_json', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['replay_plan_id'], ['replay_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replay_steps', schema=None) as batch_op:
        batch_op.create_index('idx_replay_steps_plan_order', ['replay_plan_id', 'step_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_replay_steps_replay_plan_id'), ['replay_plan_id'], unique=False)

    op.create_table('storage_operations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('page_id', sa.Text(), nullable=True),
    sa.Column('frame_id', sa.Text(), nullable=True),
    sa.Column('storage_type', sa.Text(), nullable=False),
    sa.Column('storage_scope', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('value_ref', sa.Text(), nullable=True),
    sa.Column('timestamp_ns', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['trace_events.event_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storage_operations', schema=None) as batch_op:
        batch_op.create_index('idx_storage_session_key', ['session_id', 'storage_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_operations_session_id'), ['session_id'], unique=False)

    op.create_table('edge_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('edge_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.Text(), nullable=False),
    sa.Column('source_event_id', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['graph_edges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_event_id'], ['trace_events.event_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edge_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edge_evidence_edge_id'), ['edge_id'], unique=False)

    op.create_table('network_responses',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('headers_json', sa.Text(), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=True),
    sa.Column('received_at_ns', sa.BigInteger(), nullable=False),
    sa.Column('body_hash', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['trace_events.event_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['network_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_responses_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_responses_request_id'))

    op.drop_table('network_responses')
    with op.batch_alter_table('edge_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edge_evidence_edge_id'))

    op.drop_table('edge_evidence')
    with op.batch_alter_table('storage_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_operations_session_id'))
        batch_op.drop_index('idx_storage_session_key')

    op.drop_table('storage_operations')
    with op.batch_alter_table('replay_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replay_steps_replay_plan_id'))
        batch_op.drop_index('idx_replay_steps_plan_order')

    op.drop_table('replay_steps')
    with op.batch_alter_table('network_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_requests_session_id'))

    op.drop_table('network_requests')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_session_id'))
        batch_op.drop_index('idx_edges_target_relation')
        batch_op.drop_index('idx_edges_source_relation')
        batch_op.drop_index('idx_edges_session_relation')
        batch_op.drop_index('idx_edges_confidence')

    op.drop_table('graph_edges')
    with op.batch_alter_table('value_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_value_observations_value_hash'))
        batch_op.drop_index(batch_op.f('ix_value_observations_session_id'))

    op.drop_table('value_observations')
    with op.batch_alter_table('trace_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trace_events_execution_id'))
        batch_op.drop_index('idx_events_type_time')
        batch_op.drop_index('idx_events_session_time')
        batch_op.drop_index('idx_events_execution')

    op.drop_table('trace_events')
    with op.batch_alter_table('replay_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replay_plans_session_id'))

    op.drop_table('replay_plans')
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_nodes_session_id'))
        batch_op.drop_index(batch_op.f('ix_graph_nodes_node_type'))
        batch_op.drop_index(batch_op.f('ix_graph_nodes_entity_id'))
        batch_op.drop_index('idx_graph_nodes_session_type')
        batch_op.drop_index('idx_graph_nodes_entity')

    op.drop_table('graph_nodes')
    with op.batch_alter_table('function_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_function_executions_session_id'))

    op.drop_table('function_executions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_started_at_ns'))
        batch_op.drop_index(batch_op.f('ix_sessions_source'))

    op.drop_table('sessions')
    # ### end Alembic commands ###
